on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Build documentation

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yy \
              python3-sphinx
            
          pip install sphinxjp-themes-basicstrap

      - name: Build from RST using Sphinx
        run: |
          pushd ./docs
          make singlehtml
          popd
        
      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/_build/singlehtml/'
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
